### ISSUE TITLE
4.27 build ERROR

### ISSUE THREAD

**Issue by VegetableWithChicken** [wongfei/ue4-gstreamer#13]
`已启动生成…
1>------ 已启动生成: 项目: TestAndriodEvn, 配置: Development_Editor x64 ------
1>Building TestAndriodEvnEditor...
1>Using Visual Studio 2019 14.29.30136 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133) and Windows 10.0.19041.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>Building 4 actions with 20 processes...
1>  [1/4] Module.GStreamer.cpp
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(41): error C2378: “GError”: 重定义；符号不能由 typedef 重载
1>  E:\Office_EPIC\UE_4.27\Engine\Source\Runtime\Core\Public\CoreGlobals.h(80): note: 参见“GError”的声明
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(51): error C2143: 语法错误: 缺少“;”(在“*”的前面)
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(51): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(51): error C2040: “GError”:“int”与“FOutputDeviceError *”的间接寻址级别不同
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(54): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(57): error C2143: 语法错误: 缺少“;”(在“*”的前面)
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(57): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(57): error C2040: “GError”:“int”与“FOutputDeviceError *”的间接寻址级别不同
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(59): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(61): error C2143: 语法错误: 缺少“;”(在“*”的前面)
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(61): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(61): error C2040: “GError”:“int”与“FOutputDeviceError *”的间接寻址级别不同
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(64): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(67): error C2065: “error”: 未声明的标识符
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(67): error C2182: “g_error_free”: 非法使用“void”类型
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(69): error C2143: 语法错误: 缺少“;”(在“*”的前面)
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(69): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(69): error C2040: “GError”:“int”与“FOutputDeviceError *”的间接寻址级别不同
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(69): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(69): error C2143: 语法错误: 缺少“,”(在“*”的前面)
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(69): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(72): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(72): error C2143: 语法错误: 缺少“,”(在“*”的前面)
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(80): error C2065: “err”: 未声明的标识符
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(81): error C2275: “GQuark”: 将此类型用作表达式非法
1>  C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gquark.h(36): note: 参见“GQuark”的声明
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(81): error C2146: 语法错误: 缺少“)”(在标识符“domain”的前面)
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(87): error C2065: “err”: 未声明的标识符
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(88): error C2275: “GQuark”: 将此类型用作表达式非法
1>  C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gquark.h(36): note: 参见“GQuark”的声明
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(88): error C2146: 语法错误: 缺少“)”(在标识符“domain”的前面)
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(95): error C2065: “dest”: 未声明的标识符
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(96): error C2065: “src”: 未声明的标识符
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(95): error C2182: “g_propagate_error”: 非法使用“void”类型
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(100): error C2065: “err”: 未声明的标识符
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(100): error C2182: “g_clear_error”: 非法使用“void”类型
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(104): error C2065: “err”: 未声明的标识符
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(105): error C2059: 语法错误:“const”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(110): error C2065: “dest”: 未声明的标识符
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(111): error C2065: “src”: 未声明的标识符
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gerror.h(112): error C2059: 语法错误:“const”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gthread.h(152): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(87): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(92): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(97): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(101): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(105): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(114): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(122): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(130): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(144): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(149): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(159): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(164): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(172): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(180): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(188): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(199): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(207): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(215): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(223): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(236): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(241): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(245): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gbookmarkfile.h(250): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gconvert.h(99): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gconvert.h(106): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gconvert.h(115): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gconvert.h(125): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gconvert.h(131): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gconvert.h(141): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gconvert.h(147): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gconvert.h(152): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gconvert.h(157): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gdir.h(42): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gfileutils.h(87): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gfileutils.h(92): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gfileutils.h(95): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gfileutils.h(116): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gfileutils.h(119): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gunicode.h(790): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gunicode.h(796): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gunicode.h(806): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gunicode.h(812): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gunicode.h(818): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gunicode.h(824): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(137): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(142): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(146): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(148): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(154): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(188): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(218): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(236): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(248): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(254): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(259): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(264): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(270): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(274): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(280): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(284): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(289): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/giochannel.h(293): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gkeyfile.h(72): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gkeyfile.h(78): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gkeyfile.h(83): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gkeyfile.h(90): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gkeyfile.h(96): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gkeyfile.h(100): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gkeyfile.h(104): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gkeyfile.h(114): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gkeyfile.h(122): error C2061: 语法错误: 标识符“GError”
1>C:\gstreamer\1.0\x86_64\include\glib-2.0\glib/gkeyfile.h(122): fatal error C1003: 错误计数超过 100；正在停止编译
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(45,5): error MSB3073: 命令“E:\Office_EPIC\UE_4.27\Engine\Build\BatchFiles\Build.bat TestAndriodEvnEditor Win64 Development -Project="E:\Epic_Project\TestAndriodEvn\TestAndriodEvn.uproject" -WaitMutex -FromMsBuild”已退出，代码为 6。
1>已完成生成项目“TestAndriodEvn.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========
`

**Comment by wongfei** [comment]
bUseUnityBuild = false;
bUsePCHFiles = false;

https://github.com/wongfei/ue4-gstreamer/blob/master/Source/GStreamerDemo.Target.cs#L11
