### ISSUE TITLE
Emulate incoming stream

### ISSUE THREAD

**Issue by JoneJeremiassen** [wongfei/ue4-gstreamer#15]
Hey, and thanks for reading. This isn't really an issue, but I wasn't sure how to contact you.

So I'm trying to emulate a video test stream into UE4.

Sending:
`gst-launch-1.0 -e mpegtsmux name=mux ! rtpmp2tpay ! udpsink host=127.0.0.1 port=5000 videotestsrc pattern=smpte ! "video/x-raw,width=250,height=250,framerate=60/1" ! openh264enc ! h264parse ! mux.`
![image](https://user-images.githubusercontent.com/13529002/151791996-b8dcba83-7e0f-45fb-bde0-cb5eab7abe42.png)

Receiving:
`gst-launch-1.0 -v udpsrc port=5000 ! videoparse width=250 height=250 framerate=60/1 format=8 ! autovideoconvert ! autovideosink`
![image](https://user-images.githubusercontent.com/13529002/151792103-87c627fa-2b5f-4311-aa7f-a30fc26911db.png)

I am however failing to get this videostream into UE4 and to display. Any suggestions as to what I'm doing wrong? Thanks!

**Comment by wongfei** [comment]
don't have example with mpegtsmux but this:

```
// sender
"%GSTREAMER_ROOT%\bin\gst-launch-1.0.exe" videotestsrc pattern=snow is-live=true ! video/x-raw,width=(int)1920,height=(int)1080,format=(string)RGBA,framerate=(fraction)30/1 ! nvh264enc zerolatency=true ! video/x-h264,stream-format=byte-stream ! rtph264pay config-interval=1 pt=96 ! udpsink host=127.0.0.1 port=9999

// receiver
"%GSTREAMER_ROOT%\bin\gst-launch-1.0.exe" udpsrc port=9999 caps="application/x-rtp,media=(string)video,clock-rate=(int)90000,encoding-name=(string)H264" ! queue ! rtph264depay ! avdec_h264 ! videoconvert ! autovideosink

// ue4 receiver
udpsrc port=9999 caps="application/x-rtp,media=(string)video,clock-rate=(int)90000,encoding-name=(string)H264" ! queue ! rtph264depay ! avdec_h264 ! videoconvert ! video/x-raw,width=(int)1920,height=(int)1080,format=(string)RGBA,framerate=(fraction)30/1 ! appsink name=sink
```

**Comment by Waldrin73** [comment]
I was able to setup the sender and recevier, however it doesn't seem to be receiving/displaying in UE4.

I did:
- Start sender
- Start receiver
- UE4 pipeline config -> play

![image](https://user-images.githubusercontent.com/13529002/151933688-672d7623-3458-4ee9-a406-83369334ee00.png)

![image](https://user-images.githubusercontent.com/13529002/151933812-bcf990af-3346-4ed9-a285-514c254fe458.png)
