### ISSUE TITLE
Debug Info for udpsrc

### ISSUE THREAD

**Issue by eman41** [wongfei/ue4-gstreamer#3]
Greetings!

First of all, thanks for this plugin, it's saved me a lot of research time.

For a few different pipelines, this is working exactly as intended, some examples:
`uridecodebin uri=https://www.freedesktop.org/software/gstreamer-sdk/data/media/sintel_trailer-480p.webm ! videoconvert ! video/x-raw,format=(string)RGBA ! videoconvert ! appsink name=sink`

`videotestsrc pattern=snow ! video/x-raw,width=(int)512,height=(int)512,format=(string)RGBA,framerate=(fraction)30/1 ! appsink name=sink`

However, for our application, we're ingesting a stream from a vendor with the following pipeline:
`udpsrc address=224.1.1.1 port=16384 ! application/x-rtp, media=video, clock-rate=90000, encoding-name=JPEG, payload=26 ! rtpjpegdepay ! jpegdec ! autovideosink sync=0`

My first try was to just swap the sink out to `appsink name=sink`, but I received a pipeline warning with no real info on what is wrong. Using `autovideoink` works as I would expect, when I hit play an external window pops up with the correct stream.

I'm wondering if there is something in the plugin code I could modify/change to help debug the connection. I realize some of this is GStreamer minutia, and any help you can provide would be awesome.

Thanks again!

**Comment by wongfei** [comment]
hi, maybe these pipelines would help:

[test video streamer]
gst-launch-1.0 filesrc location="test.mp4" ! decodebin ! videoconvert ! jpegenc ! jpegparse ! rtpjpegpay ! udpsink host=127.0.0.1 port=9999

[UE4 pipeline]
udpsrc address=127.0.0.1 port=9999 ! application/x-rtp, media=video, clock-rate=90000, encoding-name=JPEG, payload=26 ! rtpjpegdepay ! jpegdec ! videoconvert ! video/x-raw,format=(string)RGBA ! videoconvert ! appsink name=sink

**Comment by wongfei** [comment]
in case of error it should output something meaningful to log file (ue4-gstreamer-git\Saved\Logs\GStreamerDemo.log) and output window:

[2019.09.11-15.04.36:519][591]LogGStreamer: Error: gst_parse_launch failed -> could not link jpegdec1 to videoconvert2, jpegdec1 can't handle caps video/x-raw, format=(string)RGBA

[2019.09.11-15.04.36:519][591]LogGStreamer: Error: GstPipeline: Init FAILED

**Comment by eman41** [comment]
The additional pipeline chunks worked great. I'm still getting a warning ` GstPipeline: BUS WARNING <pipeline>` but with no other info in the log.

But it doesn't seem to be affecting the display of the stream. If it does I'll check in again!

**Comment by wongfei** [comment]
warnings can be ignored if it works and performance is good, or even disabled/commented out in func FGstPipelineImpl::OnBusMessage
