### ISSUE TITLE
Bus error

### ISSUE THREAD

**Issue by marcelherd** [wongfei/ue4-gstreamer#4]
Hi, thank you for your great work, it helps me a lot!

I'm trying to display a stream from a UDP source, but it doesn't work and the only error I get is this:

`LogGStreamer: Error: GstPipeline: BUS ERROR <pipeline1>`

Is there any way to get a more detailed description?

Pipeline config: 

`udpsrc address=localhost port=5000 ! application/x-rtp, payload=96 ! rtpjitterbuffer ! rtph264depay ! avdec_h264 ! x264enc tune=zerolatency ! appsink name=sink`

This is how I write to UDP source:

```cpp
int main(int argc, char* argv[])
{
	cv::VideoCapture cap("ksvideosrc ! videoconvert ! appsink");
	cv::VideoWriter writer("appsrc ! videoconvert ! x264enc tune=zerolatency ! video/x-h264, stream-format=byte-stream ! rtph264pay ! udpsink host=localhost port=5000", 0, (double)30, cv::Size(640, 480), true);


	cv::Mat frame;
	int key;

	while (true) {
		cap >> frame;
		if (frame.empty()) break;
// TODO: processing
		writer << frame;
		key = cv::waitKey(30);
	}
}
```

I'd highly appreciate any help!

**Comment by wongfei** [comment]
try this one to get error details:
```
/// FILE: GstPipelineImpl.cpp

///+++
static void LogGstErrorDetails(GstMessage* msg)
{
	GError* err = NULL;
	gchar* dbg_info = NULL;
	gst_message_parse_error(msg, &err, &dbg_info);
	
	GST_LOG_ERR_A("ERROR from element %s: %s\n", GST_OBJECT_NAME(msg->src), err->message);
	GST_LOG_ERR_A("Debugging info: %s\n", (dbg_info) ? dbg_info : "none");
	
	g_error_free(err);
	g_free(dbg_info);
}
///

gboolean FGstPipelineImpl::OnBusMessage(GstMessage* Message)
{
...
		case GST_MESSAGE_ERROR:
			GST_LOG_ERR_A("GstPipeline: BUS ERROR <%s>", m_Name.c_str());

			///+++
			LogGstErrorDetails(Message);
			///

			g_main_loop_quit(m_Loop);
			break;
...

```

**Comment by marcelherd** [comment]
Thank you for the quick response! Unfortunately I can't get the error to show up anymore, but it also doesn't work :/

**Comment by wongfei** [comment]
Plugin requires RGBA8 pixel format, there was an issue about udpsrc also with bus error:
https://github.com/wongfei/ue4-gstreamer/issues/3

```
[test video streamer]
gst-launch-1.0 filesrc location="test.mp4" ! decodebin ! videoconvert ! jpegenc ! jpegparse ! rtpjpegpay ! udpsink host=127.0.0.1 port=9999

[UE4 pipeline]
udpsrc address=127.0.0.1 port=9999 ! application/x-rtp, media=video, clock-rate=90000, encoding-name=JPEG, payload=26 ! rtpjpegdepay ! jpegdec ! videoconvert ! video/x-raw,format=(string)RGBA ! videoconvert ! appsink name=sink
```

Also check the native plugins for UE4:
Realsense SDKv2
https://github.com/IntelRealSense/librealsense/tree/master/wrappers/unrealengine4
Realsense SDKv1
https://github.com/GameTechDev/UE4RealSensePlugin

**Comment by marcelherd** [comment]
Thank you for your patience! Your example pipelines work great of course, but I can not get it to work with appsrc. I realize it has nothing to do with your plugin, but if you have any idea what I'm doing wrong, I'd greatly appreciate it

`appsrc ! videoconvert ! video/x-raw,format=I420 ! jpegenc ! jpegparse ! rtpjpegpay ! udpsink host=localhost port=5000`

I kind of got it to work using my previous pipeline and setting the format to RGBA as you suggested

`udpsrc address=localhost port=5000 ! application/x-rtp, payload=96 ! rtpjitterbuffer ! rtph264depay ! avdec_h264  ! videoconvert ! video/x-raw,format=(string)RGBA !  appsink name=sink`

But it does not look very good: https://i.imgur.com/7HQXaQu.png

**Comment by wongfei** [comment]
The screenshot seems to be a video format mismatch issue. Have to ensure the whole pipeline works correct. Try splitting it on minimal logical chunks and check each chunk output (or start with some very simple setup without video encoding). I'm not Gstreamer expert, can't give advice on pipeline setup.

**Comment by marcelherd** [comment]
Thanks a lot for your time and help! I'll give it a try :) Have a nice day!
