### ISSUE TITLE
Question about openCV output

### ISSUE THREAD

**Issue by dpredie** [wongfei/ue4-gstreamer#5]
Hi wongfei, this isnt really an issue but im not sure how else to contact you.  

i am exploring how to send an external openCV output to UE (i dont want to build it inside UE).  
  
  is it possible to pipe the openCV output to gstream and have this plugin ingest it? Also, UE 4.26.1 Media Framework uses Electra Media, which has some Gstream components to it, able to play HLS source, do you know what is the difference between this plugin and that?  
  
Thanks

**Comment by wongfei** [comment]
That seems possible but have to build OpenCV with GStreamer support: https://answers.opencv.org/question/202017/how-to-use-gstreamer-pipeline-in-opencv/

OpenCV/Python sender pipeline:

`out_send = cv2.VideoWriter('videotestsrc pattern=snow ! video/x-raw,width=(int)640,height=(int)480,format=(string)RGBA,framerate=(fraction)30/1 ! tcpserversink host=127.0.0.1 port=5000 sync=false', cv2.CAP_GSTREAMER, 0, 30, (640, 480), True)
`
UE4 BP_AppSink:

`tcpclientsrc host=127.0.0.1 port=5000 ! videoparse width=640 height=480 framerate=30/1 format=11 ! appsink name=sink`

Anyway I don't recommend streaming unless you forced to use it.. Just build OpenCV world static library and embed into ue4 project.

**Comment by dpredie** [comment]
Thank you wongfei. Why dont you recommend streaming? Im trying to do a DNN ONNX model in openCV, im not sure if i can have openCV dnn cuda integrated with UE. Also since it runs tight (30fps), i am thinking to have it as separate openCV app, so if i need to run it from another machine to free up UE rendering machine resource, i have the option to do that vs integrating straight in UE (and having to do UE version maintenance)

**Comment by wongfei** [comment]
Well, in case of multiple PC's maybe it's an option.
