### ISSUE TITLE
Streaming H264

### ISSUE THREAD

**Issue by 00Deez** [wongfei/ue4-gstreamer#7]
Hey Wongfei,

I've been playing around with your gstreamer plugin and it's very well put together.  However, I'm having a lot of trouble tweaking the pipeline configuration to capture and transmit video as an h264 stream.  Below is my latest attempt and when I open it up in VLC it says it's decoding audio (totally stumped). 

appsrc name=src caps=video/x-h264,format=(string)BGRA ! tcpserversink host=127.0.0.1 port=5000 sync=false

 Any input you might have would be greatly appreciated!

Regards,

Deezee

**Comment by wongfei** [comment]
sender:

appsrc name=src caps=video/x-raw,width=(int)640,height=(int)480,format=(string)BGRA,framerate=(fraction)60/1 ! queue ! nvh264enc zerolatency=true ! video/x-h264,stream-format=byte-stream ! rtph264pay config-interval=1 pt=96 ! udpsink host=127.0.0.1 port=5000

receiver:

gst-launch-1.0.exe udpsrc port=5000 caps="application/x-rtp,media=(string)video,clock-rate=(int)90000,encoding-name=(string)H264" ! rtph264depay ! avdec_h264 ! autovideosink

**Comment by wongfei** [comment]
dunno about VLC

**Comment by 00Deez** [comment]
Ah, I see... I was way off.  Thanks for the help Wongfei.  I also throw a star your way!
